import { describe, expect, it } from "vitest";
import {
  validateIngredientDocument,
  validateProductDocument,
  validateUserDocument,
} from "./firestoreCompatibility";

const company = {
  name: "Loja",
  productType: "Produto físico",
  salesChannel: "Online",
  taxRegime: "mei",
  effectiveTaxRatePct: 0,
  fixedCosts: { rent: 100 },
};
const product = {
  name: "Bolo",
  inputs: { productName: "Bolo", insumos: 2, volumeEstimado: 10, margem: 30 },
  results: {},
};
const ingredient = {
  name: "Farinha",
  purchaseUnit: "kg",
  purchaseQty: 1,
  purchasePrice: 5,
  unitsPerPackage: null,
  baseUnit: "g",
  costPerBaseUnit: 0.005,
};

describe("Firestore compatibility validator", () => {
  it("accepts documents generated by the current application", () => {
    expect(validateUserDocument({ company })).toEqual([]);
    expect(validateProductDocument(product)).toEqual([]);
    expect(validateIngredientDocument(ingredient)).toEqual([]);
  });

  it("finds legacy fields that strict rules would block on the next update", () => {
    expect(validateUserDocument({ company, legacy: true })).toContain("extra_user_fields:legacy");
    expect(validateProductDocument({ ...product, inputs: { ...product.inputs, oldTax: 5 } })).toContain("extra_input_fields:oldTax");
    expect(validateIngredientDocument({ ...ingredient, supplier: "X" })).toContain("extra_ingredient_fields:supplier");
  });

  it("finds invalid values without exposing document contents", () => {
    expect(validateProductDocument({ ...product, inputs: { ...product.inputs, insumos: -1 } })).toContain("invalid_input:insumos");
    expect(validateIngredientDocument({ ...ingredient, purchaseQty: 0 })).toContain("invalid_purchase_qty");
  });
});
